#!/usr/bin/env node

var pump = require('pump');
var stream = require('stream-wrapper');
var deleteRange = require('level-delete-range');
var index = require('../search-index');
var db = require('../db');

var i = 0;

pump(
	db.users.createValueStream(),
	stream.writable({objectMode:true}, function(user, enc, callback) {
		if (i) process.stdout.moveCursor(0, -1);
		console.log('updating', (user.username || '(registry)')+' #'+(++i)+'    ');
		index.update(user, callback);
	}),
	function(err) {
		if (err) throw err;
		deleteRange(db.updates, {}, function(err) {
			if (err) throw err;
			console.log('all indexes updated');
		});
	}
);